name: Upload to Chrome Web Store

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install npm packages
        run: npm ci

      - name: Build
        run: npm run build

      # Ajoutez l'étape d'incrémentation ici, juste avant l'étape de compression
      - name: Increment version
        run: |
          cd dist/add-border/browser  # Assurez-vous que c'est le bon chemin vers votre manifest.json
          VERSION=$(grep '"version"' manifest.json | sed 's/.*: "\(.*\)".*/\1/')
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          sed -i 's/"version": "'$VERSION'"/"version": "'$NEW_VERSION'"/' manifest.json
          echo "New version: $NEW_VERSION"
          cd ../../..  # Retour au répertoire racine

      - name: Zip
        run: |
          mkdir extension
          cp -r dist/add-border/browser/* extension/
          zip -r dist.zip extension

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true
